server.servlet.context-path=/
server.port=${API_PORT}
server.error.include-message=always
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
logging.level.org.springframework.transaction.interceptor=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTransactionManager=DEBUG